#!/bin/bash -l
#PBS -l walltime=03:00:00,nodes=1:ppn=24,pmem=2580mb
#PBS -m abe
#PBS -j oe
#PBS -M tatsurobkkuk@gmail.com

cd $PBS_O_WORKDIR 

module load intel
module load impi/intel
module load cmake

# 360 days per year with a time step of 2 steps per day:
mpiexec -np 24 -hostfile $PBS_NODEFILE ./mops \
        -numtracers 9 \
        -pickup pickup.petsc \
        -me Ae \
        -mi Ai \
        -t0 1765.0 -iter0 0 \
        -deltat_clock 0.0013888888888889 \
        -max_steps 360000 \
        -write_time_steps 7200 \
        -o po4out.petsc,dopout.petsc,oxyout.petsc,phyout.petsc,zooout.petsc,detout.petsc,no3out.petsc,dicout.petsc,alkout.petsc \
        -external_forcing \
        -use_profiles \
        -nzeuph 2 \
        -biogeochem_deltat 43200.0 -days_per_year 360.0 \
        -burial_sum_steps 720 \
        -periodic_matrix \
        -pco2atm_history TpCO2.bin,pCO2atm.bin \
        -matrix_cycle_period 1.0 -matrix_num_per_period 12 \
        -periodic_biogeochem_forcing \
        -periodic_biogeochem_cycle_period 1.0 -periodic_biogeochem_num_per_period 12 \
        -num_biogeochem_steps_per_ocean_step 8 \
        -separate_biogeochem_time_stepping \
        -time_avg -avg_start_time_step 1 -avg_time_steps 720 \
        -avg_files po4avg.petsc,dopavg.petsc,oxyavg.petsc,phyavg.petsc,zooavg.petsc,detavg.petsc,no3avg.petsc,dicavg.petsc,alkavg.petsc \
        -calc_diagnostics -diag_start_time_step 1 -diag_time_steps 720 \
        -diag_files fbgc1.petsc,fbgc2.petsc,fbgc3.petsc,fbgc4.petsc,fbgc5.petsc,fbgc6.petsc,fbgc7.petsc \
        > log
# driver options:
#  I/O:
#   -pickup_out pickup.petsc \
#   -time_file output_time.txt \
#  circulation-specific options:
#   add this option for configurations in which the forcing is rescaled because of a time-varying free surface:
#    -rescale_forcing_file Rfs \
# model-specific options:
